### ISSUE TITLE
Structure maps with 0 contacts make the match function crash

### ISSUE THREAD

**Issue by jjavier-bm** [rigdenlab/conkit#108]
## General Information
Structure maps with 0 contacts make the match function crash. It should go on with 0 TPs and 0 FNs.

- ConKit version: 0.13.2
- Python version:  >= 3.6
- Environment (if applicable): Anaconda

## Example

A minimal example to reproduce the error:
```
from conkit import io as ckio

# Parse input files
seq = ckio.read('mypath/myseq.fasta', 'fasta')[0]
strmap = ckio.read('mypath/mypdb.pdb', 'pdb')[0]
conpred = ckio.read('mypath/myconpred.psicov', 'psicov')

# Set sequence in contact prediction map
conpred.sequence = seq
conpred.set_sequence_register()

# Remove contacts from structure map
for contact in reversed(strmap):
    strmap.remove(contact.id)

# Match both
conpred.match(strmap, add_false_negatives=True, inplace=True)
```

## Traceback

The Python traceback
```
Traceback (most recent call last):

  File "/tmp/ipykernel_479769/2084760485.py", line 1, in <module>
    conpred.match(cmap, add_false_negatives=True, inplace=True)

  File "~/anaconda3/lib/python3.7/site-packages/conkit/core/contactmap.py", line 804, in match
    contact_map2_keymap = ContactMap._create_keymap(contact_map2, altloc=True)

  File "~/anaconda3/lib/python3.7/site-packages/conkit/core/contactmap.py", line 1126, in _create_keymap
    return list(zip(*contact_map_keymap_sorted))[1]

IndexError: list index out of range
```

**Comment by FilomenoSanchez** [comment]
What would be you preferred behaviour when this occurs? I'm tempted just to raise a `ValueError` and inform the user.

**Comment by jjavier-bm** [comment]
Ideally, there is not a reasonable cause to raise an error and make it crash. When matching a Contact prediction list containing a positive number of contacts with a Contact Map of 0 contacts, all the operations should still be possible (plotting, obtaining number of true positives...). Since, in this case, this match produces 0 true positives and 0 false negatives, some properties of the Contact map that use these values in the denominator may cause problems, but otherwise the object could be used as with a positive number of contacts.
