### ISSUE TITLE
TypeError when reading normal FASTA file in Python3

### ISSUE THREAD

**Issue by fsimkovic** [rigdenlab/conkit#30]
Bug report via email from Miguel Correa Marrero.

----

## General Information

- ConKit version: 0.8
- Python version: 3.6
- Other: PyPi installation

## Example

```
>>> import conkit.io
>>> conkit.io.read("aligned.fasta", "fasta")
```

## Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/felix/develop/conkit/conkit/io/__init__.py", line 141, in read
    hierarchy = parser_in.read(f_in, f_id=f_id)
  File "/home/felix/develop/conkit/conkit/io/fasta.py", line 76, in read
    elif line.startswith('#'):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by fsimkovic** [comment]
Fixed in faf64bf97005c500667fe654cc18127c70bc9c28
