### ISSUE TITLE
Unable to plot small Contact Maps

### ISSUE THREAD

**Issue by jjavier-bm** [rigdenlab/conkit#71]
## General Information

- ConKit version: 0.11.3
- Python version: 3.7
- Environment (if applicable): Anaconda

## Example

A minimal example to reproduce the error:
```
import conkit.io
import conkit.plot

maps=conkit.io.read('5hea.pdb', 'pdb')

for n in range(len(maps)):
    cmap=maps[n]
    print(n)
    file='5hea_contactmap_'+str(n)+'.flib'
    conkit.io.write(file, 'flib',hierarchy=cmap)
    fig=conkit.plot.ContactMapFigure(hierarchy=cmap, legend=True)
    file='5hea_contactmap_'+str(n)+'.png'
    fig.savefig(file)
```

## Traceback

The Python traceback
```
../anaconda3/lib/python3.7/site-packages/conkit/plot/contactmap.py:237: RuntimeWarning: divide by zero encountered in long_scalars
  tick_range = np.arange(min_max_data.min(), min_max_data.max(), gap, dtype=np.int64)
Traceback (most recent call last):

  File "<ipython-input-93-c2b3543831c8>", line 1, in <module>
    runfile('../Protein_Files/5HEA/Conkit_PDBfile/conkit_test_contacts_5hea.py', wdir='../Protein_Files/5HEA/Conkit_PDBfile')

  File "../anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "../anaconda3/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "../Protein_Files/5HEA/Conkit_PDBfile/conkit_test_contacts_5hea.py", line 24, in <module>
    fig=conkit.plot.ContactMapFigure(hierarchy=cmap, legend=True)

  File "../anaconda3/lib/python3.7/site-packages/conkit/plot/__init__.py", line 45, in ContactMapFigure
    return ContactMapFigure(*args, **kwargs)

  File "../anaconda3/lib/python3.7/site-packages/conkit/plot/contactmap.py", line 118, in __init__
    self.draw()

  File "../anaconda3/lib/python3.7/site-packages/conkit/plot/contactmap.py", line 237, in draw
    tick_range = np.arange(min_max_data.min(), min_max_data.max(), gap, dtype=np.int64)

ValueError: Maximum allowed size exceeded
```

## Notes from user

```
This problem arises when trying to plot contact maps of interfaces between two different monomers with a small amount of contacts (in loop above, that would be the second iteration). If the contact map contains a very small range of residues (<10 from min_max_data.min() to min_max_data.max() ), the definition of gap in line 236 of conkit/plot/contactmap.py yields gap=0, which cannot be used as tick distance in line 237.

There should be a minimum axis range (10) and tick distance (1) for maps with just very few contacts.
```

**Comment by fsimkovic** [comment]
issue fixed in v0.12
