### ISSUE TITLE
'Sequence' object has no attribute 'sequence'

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conkit#85]
## General Information

- ConKit version: commit ef4856027a4ae738a646f90fc1b234e0e2d5652c
- Python version: 3.8

## Example

```
$>conkit-plot cmap toxd.pdb pdb toxd.fasta fasta
```

## Traceback

```
Traceback (most recent call last):
  File "/home/filo/PycharmProjects/conkit/conkit/command_line/conkit_plot.py", line 510, in <module>
    main()
  File "/home/filo/PycharmProjects/conkit/conkit/command_line/conkit_plot.py", line 325, in main
    con.sequence = seq
AttributeError: 'Sequence' object has no attribute 'sequence'
```

**Comment by FilomenoSanchez** [comment]
Actually this is not a bug, the problem is I was giving the input in the wrong order... It should have been: 
```
$>conkit-plot cmap toxd.pdb pdb toxd.fasta fasta
```
