### ISSUE TITLE
Error when ploting distance predictions

### ISSUE THREAD

**Issue by FilomenoSanchez** [rigdenlab/conkit#86]
## General Information

- ConKit version:  commit ef4856027a4ae738a646f90fc1b234e0e2d5652c
- Python version: 3.8

## Example

```
$> conkit-plot distheat toxd.pdb pdb toxd.fasta fasta
```

## Traceback

```
Traceback (most recent call last):
  File "/home/filo/PycharmProjects/conkit/conkit/command_line/conkit_plot.py", line 510, in <module>
    main()
  File "/home/filo/PycharmProjects/conkit/conkit/command_line/conkit_plot.py", line 423, in main
    figure = conkit.plot.DistogramHeatmapFigure(distogram)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/plot/__init__.py", line 87, in DistogramHeatmapFigure
    return DistogramHeatmapFigure(*args, **kwargs)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/plot/distogramheatmap.py", line 83, in __init__
    super(DistogramHeatmapFigure, self).__init__(*args, **kwargs)
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/plot/contactmapmatrix.py", line 100, in __init__
    self.hierarchy = hierarchy
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/plot/distogramheatmap.py", line 91, in hierarchy
    if hierarchy and _isinstance(hierarchy, "Distogram"):
  File "/home/filo/.local/lib/python3.9/site-packages/conkit/plot/tools.py", line 216, in _isinstance
    return isinstance(hierarchy, hierarchy_type)
TypeError: isinstance() arg 2 must be a type or tuple of types
```

**Comment by FilomenoSanchez** [comment]
This is reproducible across all command line tools that plot distance predictions (i.e. `conkit-plot coval`, `conkit-plot distheat` and `conkit-validate`)
